# This is the Config File of BungeeTabListPlus
# You can find more detailed information on the wiki: https://github.com/CodeCrafter47/BungeeTabListPlus/wiki

# time in seconds after which the tabList will be resend to all players
# set this to -1 to disable scheduled update of the tabList
tablistUpdateInterval: 1.0

# whether tabList should be resend if a player joins or leaves the server
updateOnPlayerJoinLeave: true

# whether tablist should be resend if a player switches the server
updateOnServerChange: true

# whether to use scoreboard functions to bypass the 16 character limit
# does NOT conflict if other scoreboard plugins
useScoreboardToBypass16CharLimit: true

# You can limit the number of characters per slot here
# Color codes do not count as a character; -1 means unlimited
charLimit: -1

# Decide from where BungeeTabListPlus takes information like permissions,
# prefix, suffix and group.
# Possible values:
# AUTO        - take best source
# BUKKIT      - take information from Bukkit/Vault
# BUKKITPERMISSIONSEX      - take information from Bukkit/PermissionsEx
# BUNGEEPERMS - take information from BungeePerms
# BUNGEE      - take group from bungee, prefix from config.yml, permissions from bungee
permissionSource: AUTO

# whether to show players in spectator mode
showPlayersInGamemode3: true

# if enabled the plugin checks for new versions automatically.
# Use /BTLP to see whether a new version is available
# this does NOT automatically install an update
checkForUpdates: true

# this notifies admins (everyone with the permission `bungeetablistplus.admin`) if an update is available
notifyAdminsIfUpdateAvailable: true

# If this is set to true and the plugin encounters an issue a bug report is sent automatically
# Bug reports do not contain any sensitive or identifying information
# Bug reports contain the plugin name, plugin version and the error message that also appears in the server log
automaticallySendBugReports: true

# server Alias fo the {server} Variable
serverAlias:
  skygrid: skygrid
  survival: survival
  hub: hub

# Alias fo the {world} Variable. Match 'server:world' to an alias
worldAlias:
  survival:world: Survival
  hub:world: Spawn
  skyblock:world: Skyblock

# list servers you wish to create custom prefixes for.
# to use the custom prefixes use the {serverPrefix} variable
serverPrefixes:
  SkyBlock: '&8(&dS&8) '
  Minigames: '&8(&bM&8)'

# the prefixes used for the {prefix} variable, based upon permission groups
# IMPORTANT: these prefixes won't be used by default. see the wiki for details
prefixes:
  default: ''
  admin: '&c[A] '

# Interval (in seconds) at which all servers of your network get pinged to check whether they are online
# If you intend to use the {onlineState:SERVER} variable set this to 2 or any value you like
# setting this to -1 disables this feature
pingDelay: -1

# replacement for the {onlineState} variable if the server is online
online-text: '&2 ON'

# replacement for the {onlineState} variable if the server is offline
offline-text: '&c OFF'

# those fakeplayers will randomly appear on the tablist. If you don't put any names there then no fakeplayers will appear
fakePlayers: []

# servers which you wish to show their own tabList (The one provided by bukkit)
excludeServers:
- server2
- server7

# servers which you wish to hide from the global tabList
# Note that this is different from excludeServers above: this hides all players on the hidden servers from appearing
# on the tablist, whereas excluded servers' players are still on the BungeeTabListPlus tablist, but they do not see
# the global tab list
hiddenServers:
- server3
- server9

# players which are permanently hidden from the tab list
# you can either put your username or your uuid (with dashes) here
# don't use this. you have absolutely no reason to hide from anyone. on your own server.
hiddenPlayers: []

# Detects which servers are using a bukkit-side tabList-plugin
# and lets them show it / doesn't show the tablist provided by this plugin on these servers
# This is disabled by default because it could be accidentially triggered by other plugins (Essentials nicknames etc.)
# Warning: This is an experimental feature, it may cause unintended behaviour
autoExcludeServers: false

# Time zone to use for the {time} variable
# Can be full name like "America/Los_Angeles"
# or custom id like "GMT+8"
time-zone: America/Los_Angeles

